（1）创建随机的一维数组、二维数组，并查看相关属性。

In [318]:
import numpy as np
import random

In [319]:
# 创建一维数组
a_random_array_1 = np.random.randint(1, 10, 10)
print(a_random_array_1)

# 查看a_random_array_1的属性
print("形状 (shape):", a_random_array_1.shape)
print("数据类型 (dtype):", a_random_array_1.dtype)
print("元素数量 (size):", a_random_array_1.size)

[8 3 4 7 3 6 6 5 5 6]
形状 (shape): (10,)
数据类型 (dtype): int32
元素数量 (size): 10


In [320]:
# 创建二维数组
a_random_array_2 = np.random.randint(1, 10, (3, 6))
print(a_random_array_2)

# 查看a_random_array_2的属性
print("形状 (shape):", a_random_array_2.shape)
print("数据类型 (dtype):", a_random_array_2.dtype)
print("元素数量 (size):", a_random_array_2.size)

[[7 9 3 8 6 1]
 [5 3 6 6 7 9]
 [8 5 1 3 4 9]]
形状 (shape): (3, 6)
数据类型 (dtype): int32
元素数量 (size): 18


根据上述实验内容与要求中3.中所学的的知识array的便捷函数，创建二维数组

根据自己所创建的数组，根据4.中所学知识，实现数组的转换，相加减操作。

In [321]:
array1_reshaped = a_random_array_2.reshape(2, 5)
print(array1_reshaped)

ValueError: cannot reshape array of size 18 into shape (2,5)

In [ ]:
# 数组相加
array_sum = a_random_array_1 + a_random_array_2
print(array_sum)

In [ ]:
# 数组相减
array_diff = array1 - array2
print("Difference of Array 1 and Array 2:")
print(array_diff)

# 数组相乘
array_prod = array1 * array2
print("Element-wise product of Array 1 and Array 2:")
print(array_prod)

# 数组相除
array_div = array1 / array2
print("Element-wise division of Array 1 by Array 2:")
print(array_div)
